apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-credentials
  namespace: tools
type: Opaque
stringData:
  credentials.json: |
    { "AccountTag": "REDACTED", "TunnelSecret": "REDACTED", "TunnelID": "REDACTED" }

