#!/bin/bash
# Manual script to add monitors via web interface

echo "=========================================="
echo "UPTIME KUMA - Manual Monitor Setup"
echo "=========================================="
echo ""
echo "Visit: https://kuma.yirrasystems.com"
echo "Login with: james@yirrasystems.com"
echo ""
echo "Click the '+' button to add each monitor:"
echo ""
echo "==================== MONITOR 1 ===================="
echo "Name: 🌐 Main Site"
echo "Monitor Type: HTTP(s)"
echo "URL: https://yirrasystems.com"
echo "Heartbeat Interval: 60 seconds"
echo "Retries: 3"
echo ""
echo "==================== MONITOR 2 ===================="
echo "Name: 🔌 Backend API"
echo "Monitor Type: HTTP(s)"
echo "URL: https://yirrasystems.com/api/health"
echo "Heartbeat Interval: 60 seconds"
echo "Retries: 3"
echo ""
echo "==================== MONITOR 3 ===================="
echo "Name: 👨‍💼 Admin Panel"
echo "Monitor Type: HTTP(s)"
echo "URL: https://app.yirrasystems.com"
echo "Heartbeat Interval: 60 seconds"
echo "Retries: 3"
echo ""
echo "==================== MONITOR 4 ===================="
echo "Name: 📚 Documentation"
echo "Monitor Type: HTTP(s)"
echo "URL: https://docs.yirrasystems.com"
echo "Heartbeat Interval: 60 seconds"
echo "Retries: 3"
echo ""
echo "==================== MONITOR 5 ===================="
echo "Name: ⚙️ N8N Workflows"
echo "Monitor Type: HTTP(s)"
echo "URL: https://flows.yirrasystems.com"
echo "Heartbeat Interval: 60 seconds"
echo "Retries: 3"
echo ""
echo "==================== MONITOR 6 ===================="
echo "Name: 📦 Docker Registry"
echo "Monitor Type: HTTP(s)"
echo "URL: http://registry.drone-store.svc.cluster.local:5000/v2/"
echo "Heartbeat Interval: 60 seconds"
echo "Retries: 3"
echo ""
echo "==================== MONITOR 7 ===================="
echo "Name: 🗄️ PostgreSQL"
echo "Monitor Type: TCP Port"
echo "Hostname: postgres.drone-store.svc.cluster.local"
echo "Port: 5432"
echo "Heartbeat Interval: 60 seconds"
echo "Retries: 3"
echo ""
echo "==================== MONITOR 8 ===================="
echo "Name: ⚡ Redis"
echo "Monitor Type: TCP Port"
echo "Hostname: redis.drone-store.svc.cluster.local"
echo "Port: 6379"
echo "Heartbeat Interval: 60 seconds"
echo "Retries: 3"
echo ""
echo "=========================================="
echo "After adding all monitors, configure:"
echo "  - Notifications (Settings → Notifications)"
echo "  - Status Pages (Status Pages → Create)"
echo "=========================================="




