#!/bin/bash
# Quick reference for adding monitors to Uptime Kuma

echo "=========================================="
echo "UPTIME KUMA MONITOR CONFIGURATION"
echo "=========================================="
echo ""
echo "URL: https://kuma.yirrasystems.com"
echo ""
echo "==================== EXTERNAL SERVICES (HTTP/HTTPS) ===================="
echo ""
echo "1. Main Site"
echo "   Type: HTTP(s)"
echo "   URL: https://yirrasystems.com"
echo "   Method: GET | Interval: 60s | Retries: 3"
echo ""
echo "2. Backend API"
echo "   Type: HTTP(s)"
echo "   URL: https://yirrasystems.com/api/health"
echo "   Method: GET | Interval: 60s | Retries: 3"
echo ""
echo "3. Admin Panel"
echo "   Type: HTTP(s)"
echo "   URL: https://app.yirrasystems.com"
echo "   Method: GET | Interval: 60s | Retries: 3"
echo ""
echo "4. Documentation"
echo "   Type: HTTP(s)"
echo "   URL: https://docs.yirrasystems.com"
echo "   Method: GET | Interval: 60s | Retries: 3"
echo ""
echo "5. N8N Workflows"
echo "   Type: HTTP(s)"
echo "   URL: https://flows.yirrasystems.com"
echo "   Method: GET | Interval: 60s | Retries: 3"
echo ""
echo "6. Docker Registry"
echo "   Type: HTTP(s)"
echo "   URL: http://registry.drone-store.svc.cluster.local:5000/v2/"
echo "   Method: GET | Interval: 60s | Retries: 3"
echo ""
echo "==================== INTERNAL SERVICES (TCP PORT) ======================"
echo ""
echo "7. PostgreSQL Database"
echo "   Type: TCP Port"
echo "   Hostname: postgres.drone-store.svc.cluster.local"
echo "   Port: 5432 | Interval: 60s | Retries: 3"
echo ""
echo "8. Redis Cache"
echo "   Type: TCP Port"
echo "   Hostname: redis.drone-store.svc.cluster.local"
echo "   Port: 6379 | Interval: 60s | Retries: 3"
echo ""
echo "=========================================="
echo "COMMON SETTINGS FOR ALL MONITORS:"
echo "  - Max Retries: 3"
echo "  - Retry Interval: 60 seconds"
echo "  - Timeout: 48 seconds"
echo "=========================================="
echo ""
echo "To add monitors, visit https://kuma.yirrasystems.com and click '+' button"
echo ""



