apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  labels:
    app.kubernetes.io/name: mcp-server
spec:
  selector:
    app.kubernetes.io/name: mcp-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP

